version: "3.10"
services:
  backend:
    image: llm-base:v1.0
    container_name: llm-workbench
    restart: always
    # ports:
    #   - "8501:8501"
    volumes:
      - /home/xulang/project/streamlit:/workspace
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    networks:
      - network-backend
    shm_size: '2gb'
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host

networks:
  network-backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.111.1.0/24
          gateway: 10.111.1.1